/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Divider: typeof import('primevue/divider')['default']
    FloorCanvas: typeof import('./src/components/FloorCanvas.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
