"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed hosts from environment (comma-separated)
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'location_analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # MUST be before CommonMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.getenv(
        'CORS_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000'
    ).split(',') if origin.strip()
]

# Allow all origins (development) - disable in production via env var
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True').lower() in ('true', '1', 'yes')


# =============================================================================
# NEST SCORE — Centralna konfiguracja aplikacji
# Wartości czytane przez location_analysis.app_config.get_config()
# =============================================================================
NEST_SCORE_CONFIG = {
    # --- Overpass API ---
    'OVERPASS_URL': os.getenv('OVERPASS_URL', 'https://overpass-api.de/api/interpreter'),
    'OVERPASS_FALLBACK_URLS': os.getenv(
        'OVERPASS_FALLBACK_URLS',
        'https://lz4.overpass-api.de/api/interpreter,https://z.overpass-api.de/api/interpreter,https://maps.mail.ru/osm/tools/overpass/api/interpreter'
    ),
    'OVERPASS_TIMEOUT': int(os.getenv('OVERPASS_TIMEOUT', '60')),

    # --- Google Places API ---
    'GOOGLE_PLACES_ENABLED': os.getenv('GOOGLE_PLACES_ENABLED', 'true'),
    'GOOGLE_PLACES_API_KEY': os.getenv('GOOGLE_PLACES_API_KEY', ''),
    'GOOGLE_MAX_RETRIES': int(os.getenv('GOOGLE_MAX_RETRIES', '2')),

    # --- Domyślne flagi analizy ---
    'DEFAULT_ENRICHMENT': os.getenv('DEFAULT_ENRICHMENT', 'false'),
    'DEFAULT_FALLBACK': os.getenv('DEFAULT_FALLBACK', 'true'),
    'DEFAULT_POI_PROVIDER': os.getenv('DEFAULT_POI_PROVIDER', 'hybrid'),
    'DEFAULT_RADIUS': int(os.getenv('DEFAULT_RADIUS', '500')),

    # --- Sekcje raportu (toggles) ---
    'REPORT_AIR_QUALITY': os.getenv('REPORT_AIR_QUALITY', 'true'),
    'REPORT_NOISE_ANALYSIS': os.getenv('REPORT_NOISE_ANALYSIS', 'false'),
    'REPORT_AI_INSIGHTS': os.getenv('REPORT_AI_INSIGHTS', 'true'),
    'REPORT_NATURE_METRICS': os.getenv('REPORT_NATURE_METRICS', 'true'),
    'REPORT_DATA_QUALITY': os.getenv('REPORT_DATA_QUALITY', 'true'),

    # --- Air Quality ---
    'AIR_QUALITY_PROVIDER': os.getenv('AIR_QUALITY_PROVIDER', 'open_meteo'),
    'AIR_QUALITY_ENABLED': os.getenv('AIR_QUALITY_ENABLED', 'true'),

    # --- Rate Limiting ---
    'RATE_LIMIT_PER_MINUTE': int(os.getenv('RATE_LIMIT_PER_MINUTE', '5')),
    'RATE_LIMIT_PER_HOUR': int(os.getenv('RATE_LIMIT_PER_HOUR', '30')),

    # --- Cache TTLs (sekundy) ---
    'CACHE_TTL_LISTING': int(os.getenv('CACHE_TTL_LISTING', '3600')),
    'CACHE_TTL_POIS': int(os.getenv('CACHE_TTL_POIS', '604800')),
    'CACHE_TTL_GOOGLE_DETAILS': int(os.getenv('CACHE_TTL_GOOGLE_DETAILS', '604800')),
    'CACHE_TTL_GOOGLE_NEARBY': int(os.getenv('CACHE_TTL_GOOGLE_NEARBY', '259200')),
}


# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Logging — structured key=value format for location_analysis pipeline
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'structured': {
            # StructuredLogger already emits key=value lines; keep formatter minimal
            'format': '{message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'structured_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'location_analysis': {
            'handlers': ['structured_console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Mute noisy third-party loggers
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'requests': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'google': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
