# Generated by Django 5.2.10 on 2026-01-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Layout', max_length=255)),
                ('layout_data', models.JSONField(blank=True, default=dict, help_text='JSON structure: {walls: [...], objects: [...], doors: [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
