# Generated by Django 5.2.10 on 2026-01-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nazwa mieszkania, np. '2-pokojowe Poznań, ul. Lipowa 5'", max_length=255)),
                ('address', models.CharField(blank=True, help_text='Adres mieszkania', max_length=512)),
                ('area_sqm', models.FloatField(blank=True, help_text='Powierzchnia w m²', null=True)),
                ('rooms', models.IntegerField(blank=True, help_text='Liczba pokoi', null=True)),
                ('description', models.TextField(blank=True, help_text='Opis mieszkania')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mieszkanie',
                'verbose_name_plural': 'Mieszkania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Layout', 'verbose_name_plural': 'Layouty'},
        ),
        migrations.RemoveField(
            model_name='layout',
            name='name',
        ),
        migrations.AddField(
            model_name='layout',
            name='image',
            field=models.ImageField(blank=True, help_text='Zdjęcie/PDF rzutu mieszkania', null=True, upload_to='layouts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='layout',
            name='scale_cm_per_px',
            field=models.FloatField(blank=True, help_text='Skala: ile cm w rzeczywistości na 1 piksel na obrazie', null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON struktura: {walls: [...], points: [...], scale_cm_per_px: ...}'),
        ),
        migrations.AddField(
            model_name='layout',
            name='flat',
            field=models.OneToOneField(blank=True, help_text='Powiązane mieszkanie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='flat_management.flat'),
        ),
    ]
