# Generated by Django 5.2.10 on 2026-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_analysis', '0003_add_persona_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationanalysis',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores per kategoria z pełnym breakdown (nature_place, nature_background, etc.)'),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='profile_config_version',
            field=models.IntegerField(default=1, help_text='Wersja konfiguracji profilu użyta do analizy'),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='profile_key',
            field=models.CharField(db_index=True, default='family', help_text='Klucz profilu scoringu (family, urban, quiet_green, remote_work, active_sport, car_first)', max_length=30),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='scoring_debug',
            field=models.JSONField(blank=True, default=dict, help_text='Debug info: wkłady, promienie, krzywe spadku (tylko dev)'),
        ),
        migrations.AlterField(
            model_name='locationanalysis',
            name='user_profile',
            field=models.CharField(choices=[('family', 'Rodzina'), ('urban', 'Singiel / City Life'), ('investor', 'Inwestor')], default='family', help_text='[LEGACY] Profil użytkownika - użyj profile_key', max_length=20),
        ),
    ]
