# Generated by Django 5.2.10 on 2026-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_analysis', '0004_add_profile_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationanalysis',
            name='ai_insights_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated decision insights (summary, attention_points, verification_checklist)'),
        ),
    ]
