# Generated by Django 5.2.10 on 2026-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_analysis', '0005_add_ai_insights_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationanalysis',
            name='rescore_count',
            field=models.IntegerField(default=0, help_text='Ile razy zmieniono profil na tym raporcie'),
        ),
        migrations.AddField(
            model_name='locationanalysis',
            name='rescore_limit',
            field=models.IntegerField(default=3, help_text='Maksymalna liczba zmian profilu per raport'),
        ),
    ]
