/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CustomDataTable: typeof import('./components/DataTable/CustomDataTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FlatCreateForm: typeof import('./components/Flats/FlatCreateForm.vue')['default']
    FlatDetailCard: typeof import('./components/Flats/FlatDetailCard.vue')['default']
    FlatsGallery: typeof import('./components/Flats/FlatsGallery.vue')['default']
    FloatingConfigurator: typeof import('./components/FloatingConfigurator.vue')['default']
    FooterDynamicDialog: typeof import('./components/DataTable/FooterDynamicDialog.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout2DPreview: typeof import('./components/Layouts/Layout2DPreview.vue')['default']
    LayoutImportForm: typeof import('./components/Layouts/LayoutImportForm.vue')['default']
    LayoutTraceCanvas: typeof import('./components/Layouts/LayoutTraceCanvas.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
